### ISSUE TITLE
No module named mbot_world_model_ros.gpsr_dict

### ISSUE THREAD

**Issue by ErickKramer** [socrob/mbot_natural_language_processing#11]
I pulled the last changes from yesterday, but still got the error I commented to Oscar last week. 
[Error message] 
File "/home/kramer/Documents/ROS/catkin_ws/src/mbot_natural_language_processing/mbot_nlu/common/src/mbot_nlu/phrases.py", line 7, in <module>
    from mbot_world_model_ros.gpsr_dict import slots_dict
ImportError: No module named mbot_world_model_ros.gpsr_dict

When running the launch file:
roslaunch mbot_nlu mbot_nlu.launch nlu_classifier:=mithun_gpsr_robocup

It runs the phrases.py file, which contains an import of the mbot_world_model_ros file, which I have not been able to find anywhere.

**Comment by oscar-lima** [comment]
@Balussery please remove any dependency to mbot_world_model package such that mbot_natural_language_processing repo can be used standalone

**Comment by thetaleofnarutouzumaki** [comment]
@ErickKramer Could you please copy paste the full error code? Thanks.

**Comment by thetaleofnarutouzumaki** [comment]
@oscar-lima currently there is no dependency as far as I know. But I'll know once I get the complete error log. thanks.

**Comment by thetaleofnarutouzumaki** [comment]
@ErickKramer found the problem. I will try to solve and push today. I would still be glad to get the full error log, thanks.

**Comment by thetaleofnarutouzumaki** [comment]
@ErickKramer Let me know if it has solved the issue. Thanks.
